CREATE TABLE [dbo].[TestDeckOfCardsShuffleUnitTestResult]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [TWO_THREE_FOUR] INT NOT NULL, 
    [TWO_FOUR_THREE] INT NOT NULL, 
    [THREE_TWO_FOUR] INT NOT NULL, 
    [THREE_FOUR_TWO] INT NOT NULL, 
    [FOUR_TWO_FOUR] INT NOT NULL, 
    [FOUR_THREE_FOUR] INT NOT NULL
)
